### ISSUE TITLE
Missing assets in latest releases

### ISSUE THREAD

**Issue by EdDev** [kubevirt/cluster-network-addons-operator#1353] opened 2022-05-18 03:07 UTC
**What happened**:
Since v0.75.0 release, only the source code is included in the release assets.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by RamLavi** [comment] 2022-05-19 06:58
duplicate of https://github.com/kubevirt/cluster-network-addons-operator/issues/1301

Updated assets

**Closed by RamLavi** 2022-05-19 06:58 UTC
